name: Publish docs via GitHub Pages

# Only run on new tags
on:
  push:
    tags:
      - '*'
  workflow_dispatch:


jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v5

      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[psycopg-binary,docs]"

      - name: Set module version
        id: module
        run: |
          echo version=$(python -c'import titiler.pgstac; print(titiler.pgstac.__version__)') >> $GITHUB_OUTPUT

      - name: Configure Git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Fetch gh-pages repository
        run: |
          git fetch origin gh-pages --depth=1

      - name: Deploy documentation and update alias for latest
        run: |
          mike deploy ${{ steps.module.outputs.version}} latest --push --update-aliases --config-file docs/mkdocs.yml
